### PR TITLE
refactor: site enrich to send to placement queue

### PR DESCRIPTION
**Pull request by Judge40**
When a site is received its related placements should be sent to the
placement queue instead of performing the existing enrich on all
placements at once.
This allows individual placements to be processed instead of the site
triggering large batches of placements which can not easily be
processed.

TIS21-1673

### CODE REVIEW

**Comment by Judge40** [comment]
Creating as draft due to dependency on #126

**Review by JosephKelly — APPROVED** [review]
I'm assuming the `populateSiteDetails()` is happening elsewhere now.

**Comment by Marcellofabbri** [comment]
Would I need to pull the containers again in order to try it empirically locally with localstack?

**Comment by Judge40** [comment]
> I'm assuming the `populateSiteDetails()` is happening elsewhere now.

Everything will just get treated as a placement load.
So it will happen as part of `enrichPlacementWithRelatedSite` called by the top level placement enrich

**Comment by Judge40** [comment]
> Would I need to pull the containers again in order to try it empirically locally with localstack?

You'll need to pull the latest dev-handbook changes for the extra queue in localstack. Other than that only this sync project has changed, so no need to pull latest containers of any other services.

**Pull request merged**
